#!/bin/bash

# scotty-rel - Scotty RELOADED Network Management Tool
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2014        (C) IBH IT-Service GmbH [http://www.ibh.de/OSS/Scotty]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

. ${1:-/etc/scotty-rel/paths.conf}

function err {
    logger -s -t scotty-rel -- "Configuration error: $@"
    exit 1
}

S2HFN=`tempfile -p s2h -s xml`
if [ ! -e "$CFGDIR/views.xml" ]; then
    rm "$S2HFN"
    err views.xml not found "($CFGDIR/views.xml)"
fi

xsltproc -o "$S2HFN" "$XSLDIR/views2hosts.xsl" "$CFGDIR/views.xml" || err xsltproc processing failed on $CFGDIR/views.xml

perl -nMSocket -e 'while(/##([^<#]+)##/) {$h=inet_ntoa(inet_aton($1)); s/##$1##/$h/g;} print;' < "$S2HFN" > "$CFGDIR/hosts.xml.new" || err could not create views configuration
