#!/usr/bin/perl

# scotty-rel - Scotty RELOADED Network Management Tool
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2012 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

use strict;
use warnings;

use File::Basename;
use Text::Template;

my $template = shift || die;
my $output = shift || die;
my $viewdir = shift || die;

my $t = Text::Template->new(SOURCE => $template)
    or die "Couldn't construct template: $Text::Template::ERROR\n";

my %views;
foreach my $view (<$viewdir/*.svg>) {
    my $bn = basename($view);
    my $id = $bn;
    $id =~ s/\.svg$//i;
    $views{$id} = $bn;
}

open(HOUT, '>', $output) || die "Failed opening output file '$output': $!\n";
my $res = $t->fill_in(
    OUTPUT => \*HOUT,
    HASH => {views => \%views},
);
close(HOUT);

die "Couldn't fill in template: $Text::Template::ERROR\n" unless (defined($res));
