#!/bin/bash

. ${1:-/etc/scotty-rel/paths.conf}

function err {
    logger -s -t scotty-rel -- "Configuration error: $@"
    exit 1
}

SRVFN=`tempfile -p srv -s xml`
V2SFN=`tempfile -p v2s -s xml`
echo '<views>' > "$SRVFN"
for fn in "$VIEWSDIR/"*.svg; do
    if [ ! -e "$fn" ]; then
	rm "$SRVFN"
	rm "$V2SFN"
	err no views found "($VIEWSDIR/*.svg)"
    fi

    view=`basename "$fn"`
    xsltproc -stringparam view "${view:0:-4}" -o "$V2SFN" "$XSLDIR/view2services.xsl" "$fn" || err xsltproc processing failed on $fn
    tail -n +2 "$V2SFN" >> "$SRVFN"
done
rm "$V2SFN"
echo '</views>' >> "$SRVFN"

mv "$SRVFN" "$CFGDIR/views.xml" || err could not create views configuration
