#!/bin/bash

# scotty-rel - Scotty RELOADED Network Management Tool
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2012 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

. ${1:-/etc/scotty-rel/paths.conf}

function err {
    logger -s -t scotty-rel -- "Configuration error: $@"
    exit 1
}

SRVFN=`tempfile -p srv -s xml`
V2SFN=`tempfile -p v2s -s xml`
echo '<views>' > "$SRVFN"
for fn in "$VIEWSDIR/"*.svg; do
    if [ ! -e "$fn" ]; then
	rm "$SRVFN"
	rm "$V2SFN"
	err no views found "($VIEWSDIR/*.svg)"
    fi

    view=`basename "$fn"`
    xsltproc -stringparam view "${view%.svg}" -o "$V2SFN" "$XSLDIR/view2services.xsl" "$fn" || err xsltproc processing failed on $fn
    tail -n +2 "$V2SFN" >> "$SRVFN"

    xsltproc -o "$VIEWSWWWDIR/$view" "$XSLDIR/prepare-view.xsl" "$fn" || err xsltproc processing failed on $fn
done
rm "$V2SFN"
echo '</views>' >> "$SRVFN"

mv "$SRVFN" "$CFGDIR/views.xml" || err could not create views configuration
