#!/usr/bin/env perl

# scotty-rel - Scotty RELOADED Network Management Tool
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2012 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

use Mojolicious::Lite;
use JSON;
use IO::Socket;

get '/' => sub {
  my $self = shift;
  $self->render_static('index.html');
};

websocket '/ws' => sub {
    my $self = shift;
    $self->send({text => "scotty"});

    $self->on(
	message => sub {
	    my ($self, $msg) = @_;

	    if($msg eq 'getmap') {
		my $client = IO::Socket::UNIX->new(
		    Peer => '/tmp/scotty-rel',
		    Type => SOCK_STREAM,
		) or die $@;
		my $map = <$client>;
		close($client);
		chomp($map);

		$self->send(encode_json({
		    op => 'map',
		    pl => $map,
		}));
	    }
	},
    );
};

app->start;
