#!/usr/bin/perl

use strict;
use warnings;

use IO::Socket;

my $client = IO::Socket::INET->new(
    PeerAddr => '127.0.0.1',
    PeerPort => 1701,
    Proto    => 'tcp',
) or die $@;

while(<$client>) {
    print;
}
